Prepare logger overlay
DolbyIO/comms-sdk-react-native pull request #160
Opened 2023-05-25 12:06 UTC by mateuszglapiak-dolby

2023-05-30 15:35 UTC, graduad requested changes
I was also wondering:

1. Can the user move the logger button on the screen?
2. Can the user tap through the logger view?

2023-05-30 15:35 UTC, graduad commented on example/src/utils/Logger/Logger.ts
> +import { BehaviorSubject } from 'rxjs';
I have not seen `rxjs` used in the SDK or example app. It must be a dependency of a dependency. So if this the dependency that uses it stops to do so, it will no longer be included in the list of dependencies, and hence it will not be available for us to us.

I am a bit uneasy about this situation, and am wondering if we could make this work without the use of this package. Let's discuss.

2023-06-01 12:43 UTC, mateuszglapiak-dolby commented on example/src/utils/Logger/Logger.ts
> +import { BehaviorSubject } from 'rxjs';
Updated the code to not use `rxjs`

2023-06-02 13:34 UTC, graduad approved these changes

2023-06-02 13:43 UTC, merged