Renamed cancel method and changed return type.
DolbyIO/comms-sdk-react-native pull request #245
Opened 2023-08-09 12:19 UTC by mpozy

2023-08-09 13:40 UTC, graduad commented on src/services/audio/AudioPreview.ts
> +    return this._audioPreview.stop();
Is iOS still working?

2023-08-09 13:56 UTC, mpozy commented on src/services/audio/AudioPreview.ts
> +    return this._audioPreview.stop();
Not this function.

2023-08-10 10:47 UTC, graduad requested changes
Please rename the `RecorderStatus` to be inline with the native SDKs.

2023-08-10 11:00 UTC, mpozy commented
> Please rename the `RecorderStatus` to be inline with the native SDKs.

Done.

2023-08-10 12:42 UTC, graduad requested changes

2023-08-10 12:42 UTC, graduad commented on src/services/audio/AudioPreview.ts
>    }
Where are you checking for a false return from `this._audioPreview.stop();`? Don't we need to throw an error in case of a return value that is false?

2023-08-10 12:58 UTC, graduad commented on src/services/audio/AudioPreview.ts
>    }
Agreed with @mpozy that the throwing should be done on the native side. iOS wrapper is being updated .

2023-08-10 13:16 UTC, graduad approved these changes

2023-08-10 13:21 UTC, merged